// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace WallsByPerimeter
{
    public class WallsByPerimeterInputs: S3Args
    {
		/// <summary>
		/// The Thickness of the walls
		/// </summary>
		[JsonProperty("Wall Thickness")]
		public double WallThickness {get;}



        /// <summary>
        /// Construct a WallsByPerimeterInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public WallsByPerimeterInputs() : base()
        {
			this.WallThickness = 5;

        }


        /// <summary>
        /// Construct a WallsByPerimeterInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public WallsByPerimeterInputs(double wallThickness, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.WallThickness = wallThickness;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}