// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace SubdivideSlabNew
{
    public class SubdivideSlabNewOutputs: ResultsBase
    {
		/// <summary>
		/// Number of regions.
		/// </summary>
		[JsonProperty("Count")]
		public double Count {get;}

		/// <summary>
		/// number of columns
		/// </summary>
		[JsonProperty("ColCount")]
		public double ColCount {get;}


        
        /// <summary>
        /// Construct a SubdivideSlabNewOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public SubdivideSlabNewOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a SubdivideSlabNewOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public SubdivideSlabNewOutputs(double count, double colCount): base()
        {
			this.Count = count;
			this.ColCount = colCount;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}