// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace FacadeByEnvelopeNew
{
    public class FacadeByEnvelopeNewOutputs: ResultsBase
    {
		/// <summary>
		/// Total facade panels.
		/// </summary>
		[JsonProperty("Panel Quantity")]
		public double PanelQuantity {get;}


        
        /// <summary>
        /// Construct a FacadeByEnvelopeNewOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public FacadeByEnvelopeNewOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a FacadeByEnvelopeNewOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public FacadeByEnvelopeNewOutputs(double panelquantity): base()
        {
			this.PanelQuantity = panelquantity;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}