//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Spatial;
using Elements.Validators;
using Elements.Serialization.JSON;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>Represents an abstract program type, with a name and symbolic color</summary>
    [JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ProgramType : Element
    {
        [JsonConstructor]
        public ProgramType(Color @programColor, string @programName, System.Guid @id = default, string @name = null)
            : base(id, name)
        {
            this.ProgramColor = @programColor;
            this.ProgramName = @programName;
            }
        
        // Empty constructor
        public ProgramType()
            : base()
        {
        }
    
        /// <summary>A symbolic color with which to represent this program</summary>
        [JsonProperty("Program Color", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Color ProgramColor { get; set; }
    
        /// <summary>The name of this program type</summary>
        [JsonProperty("Program Name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ProgramName { get; set; }
    
    
    }
}